---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmRepository
metadata:
  name: helloworld-helm
  namespace: default
spec:
  provider: generic
  type: "oci"
  interval: 5m0s
  url: oci://ghcr.io/ariehm/helloworld/helloworld-helm
  secretRef:
    name: ghcr-cred
---
apiVersion: source.toolkit.fluxcd.io/v1beta2
kind: HelmChart
metadata:
  name: helloworld-helm
  namespace: default
spec:
  interval: 1m0s
  chart: helloworld-helm
  reconcileStrategy: ChartVersion
  sourceRef:
    kind: HelmRepository
    name: helloworld-helm
  version: '0.1.0'
---
apiVersion: helm.toolkit.fluxcd.io/v2beta2
kind: HelmRelease
metadata:
  name: helloworld-helm-release
  namespace: default
spec:
  interval: 1m
  chart:
    spec:
      chart: helloworld-helm
      version: '0.1.0'
      sourceRef:
        kind: HelmRepository
        name: helloworld-helm-chart-repo
        namespace: default
      interval: 1m
  values:
    replicaCount: 2

