apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: apps
  namespace: flux-system
spec:
  interval: 10m0s
  # This is a way to tell flux/k8s to go load other stuff first
  # but I'm not copying in the `infra-configs` thing for this demo repo
  # Leaving this here for future reference, though.
  #
  # Examples taken liberally from:
  # * https://github.com/fluxcd/flux2-kustomize-helm-example
  #
  # dependsOn:
  #   - name: infra-configs
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: ./apps/staging
  prune: true
  wait: true
  timeout: 5m0s
